/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiCorpusRouteImport } from './routes/api/corpus'
import { Route as ApiAnswerRouteImport } from './routes/api/answer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorpusRoute = ApiCorpusRouteImport.update({
  id: '/api/corpus',
  path: '/api/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnswerRoute = ApiAnswerRouteImport.update({
  id: '/api/answer',
  path: '/api/answer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/answer': typeof ApiAnswerRoute
  '/api/corpus': typeof ApiCorpusRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/answer': typeof ApiAnswerRoute
  '/api/corpus': typeof ApiCorpusRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/answer': typeof ApiAnswerRoute
  '/api/corpus': typeof ApiCorpusRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/answer'
    | '/api/corpus'
    | '/api/history'
    | '/api/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/answer' | '/api/corpus' | '/api/history' | '/api/search'
  id:
    | '__root__'
    | '/'
    | '/api/answer'
    | '/api/corpus'
    | '/api/history'
    | '/api/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnswerRoute: typeof ApiAnswerRoute
  ApiCorpusRoute: typeof ApiCorpusRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corpus': {
      id: '/api/corpus'
      path: '/api/corpus'
      fullPath: '/api/corpus'
      preLoaderRoute: typeof ApiCorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/answer': {
      id: '/api/answer'
      path: '/api/answer'
      fullPath: '/api/answer'
      preLoaderRoute: typeof ApiAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnswerRoute: ApiAnswerRoute,
  ApiCorpusRoute: ApiCorpusRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
